apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-oppdrag-proxy
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 2000m
      memory: 3072Mi
    requests:
      cpu: 80m
      memory: 1536Mi
  ingresses:
    - https://sokos-oppdrag-proxy.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics

