apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-mikrofrontend-api
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 9500
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  secureLogs:
    enabled: true
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 2000m
      memory: 3072Mi
    requests:
      cpu: 80m
      memory: 1536Mi
  ingresses:
    - https://sokos-mikrofrontend-api.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: sokos-op-fasade
          cluster: dev-gcp
          namespace: okonomi
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
  env:
    - name: USE_AUTHENTICATION
      value: "true"
    - name: PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql


